name: Save Source Code

on:
  workflow_call:


jobs:
  save-source-code:
    runs-on: ubuntu-latest  # Use Ubuntu para salvar o código

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Save relevant source code as artifact
        uses: actions/upload-artifact@v4
        with:
          name: source-code
          path: |
            .                     # Diretório raiz
            !build/               # Excluindo a pasta build
            !ios/                 # Excluindo a pasta ios
            !android/             # Excluindo a pasta android
            !.dart_tool/          # Excluindo a pasta .dart_tool
            !*.log                # Excluindo arquivos de log
