name: Save Source Code

on:
  workflow_call:


jobs:
  save-source-code:
    runs-on: ubuntu-latest  # Use Ubuntu para salvar o código

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Save relevant source code as artifact
        uses: actions/upload-artifact@v4
        with:
          name: source-code
          path: |
            ./*                   
            !**/build/**          
            !**/ios/**            
            !**/android/**         
            !**/.dart_tool/**      
            !**/*.log                 
